<?php

namespace AppBundle\Repository;

/**
 * FotoLugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoLugarRepository extends \Doctrine\ORM\EntityRepository
{
}
