imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UsuarioBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.lugar_image: ./uploads/images/lugar
    app.path.lugar_personas_images: /uploads/images/lugar/personas

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.pdo
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UsuarioBundle\Entity\Usuario
    from_email:
        address: no-reply@site.com.
        sender_name: No Reply Site.com

#VichUpload
vich_uploader:
    db_driver: orm
    mappings:
        lugar_image:
            uri_prefix:         %app.path.lugar_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/lugar
            namer:              vich_uploader.namer_origname
        lugar_personas_images:
            uri_prefix:         %app.path.lugar_personas_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/lugar/personas
            namer:              vich_uploader.namer_origname

easy_admin:
    site_name: MisPlaces
    design:
        brand_color: '#007FFF'
        menu:
            - { label: 'Estadisticas' }
            - { label: 'Generales', route: 'app_estadisticas' }
            - { label: 'Históricos', route: 'app_estadisticas_historicos' }
            - { label: 'Tiempo Real', route: 'app_estadisticas_tiempo_real' }

            # - Category
            - { label: 'Administración' }
            - Persona
            - Categoria
            - Lugar
    entities:
        Persona:
            class: AppBundle\Entity\Persona
            label: 'Personas'
            list:
                title: "Personas"
            form:
                fields: ['nombre', 'apellido', 'sexo', 'telefonoPrincipal', 'telefonoSecundario','cargo','usuario','activo']

        Categoria:
            class: AppBundle\Entity\Categoria
            label: 'Categorías'
            list:
                title: "Categorías"
            form:
                fields: ['nombre', 'descripcion', 'icono' ,'categoriaPadre', 'activo']
        Lugar:
            class: AppBundle\Entity\Lugar
            label: 'Lugares'
            list:
                title: "Lugares"
                fields:
                   - { property: 'id' }
                   - { property: 'categoria' }
                   - { property: 'nombre' }
                   - { property: 'latitud' }
                   - { property: 'longitud' }
                   - { property: 'imageName', label: 'Img. Principal', type: 'image', base_path: '%app.path.lugar_image%' }

            form:
                fields:
                   - { property: 'categoria' }
                   - { property: 'nombre' }
                   - { property: 'resumen' }
                   - { property: 'cuerpo' }
                   - { property: 'imageFile', type: 'vich_image' }
                   - { property: 'tipo' }
                   - { property: 'direccion' }
                   - { property: 'latitud' }
                   - { property: 'longitud' }
                   - { property: 'telefono' }
                   - { property: 'celular' }
                   - { property: 'email' }
                   - { property: 'facebook' }
                   - { property: 'twitter' }
                   - { property: 'instagram' }
                   - { property: 'youtube' }
                   - { property: 'fechaEventoInicio' }
                   - { property: 'fechaEventoFin' }
                   - { property: 'fechaVisibleDesde' }
                   - { property: 'fechaVisibleHasta' }
